### ISSUE TITLE
File not found traceback to long

### ISSUE THREAD

**Issue by Viddesh1** [microsoft/markitdown#124]
```python
from markitdown import MarkItDown

md = MarkItDown()
result = md.convert("test.xlsx") # if text.xlsx file does not exist.
print(result.text_content)
```

if the test.xlsx file does not exists then traceback can become too long and uses pandas to check if the file exists or not using open() method.

```
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\pdfextract\VK\two.py", line 4, in <module>
    result = md.convert("test.xlsx")
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\pdfextract\markitdown\src\markitdown\_markitdown.py", line 1302, in convert       
    return self.convert_local(source, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\pdfextract\markitdown\src\markitdown\_markitdown.py", line 1322, in convert_local 
    return self._convert(path, extensions, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\pdfextract\markitdown\src\markitdown\_markitdown.py", line 1463, in _convert      
    raise FileConversionException(
markitdown._markitdown.FileConversionException: Could not convert 'test.xlsx' to Markdown. File type was recognized as ['.xlsx']. While converting the file, the following error was encountered:

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\pdfextract\markitdown\src\markitdown\_markitdown.py", line 1447, in _convert      
    res = converter.convert(local_path, **_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\pdfextract\markitdown\src\markitdown\_markitdown.py", line 726, in convert        
    sheets = pd.read_excel(local_path, sheet_name=None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\pdfextract\.venv\Lib\site-packages\pandas\io\excel\_base.py", line 495, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "C:\Users\Admin\Desktop\pdfextract\.venv\Lib\site-packages\pandas\io\excel\_base.py", line 1550, in __init__
    ext = inspect_excel_format(
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\pdfextract\.venv\Lib\site-packages\pandas\io\excel\_base.py", line 1402, in inspect_excel_format
    with get_handle(
         ^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\pdfextract\.venv\Lib\site-packages\pandas\io\common.py", line 882, in get_handle  
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test.xlsx'
```

**Comment by Viddesh1** [comment]
After adding the try and except if file not found. Raises FileNotFoundError

```
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\pdfextract\markitdown\src\markitdown\_markitdown.py", line 1289, in convert       
    with open(source, 'r'):
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test.xlsx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\pdfextract\VK\two.py", line 4, in <module>
    result = md.convert("test.xlsx")
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\pdfextract\markitdown\src\markitdown\_markitdown.py", line 1292, in convert       
    raise FileNotFoundError
FileNotFoundError
```

**Comment by afourney** [comment]
I believe this should be addressed in 0.1.0a1.

I also don't think that long stack traces are a problem -- we want the to reflect where the error occurred.

On the other hand, I could certainly be convinced that the CLI should print nicer messages for common errors.
