### ISSUE TITLE
Can't convert unicode char ✓ (U+2713)

### ISSUE THREAD

**Issue by Gamecraft400** [microsoft/markitdown#138]
I try to convert a old docx file with markitdown.

charmap return this error : 

`
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "[Hide]\Python\Python313\Scripts\markitdown.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "[Hide]\Python313\Lib\site-packages\markitdown\__main__.py", line 43, in main
    print(result.text_content)
    ~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "[Hide]\Python\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u261e' in position 5820: character maps to <undefined>
`

**Comment by l-lumin** [comment]
#116

**Comment by ebrahym-hol** [comment]
i want know how can hacking the software

**Comment by Gamecraft400** [comment]
I've found a solution. In my case, my docx document is encoded in UTF8, 

I've just set PYTHONUTF8=1

And it works now

**Comment by jromal** [comment]
This should be the default. UTF-8 should be the default everywhere. We are hading towards 2025. This is not 1996.

**Comment by doggy8088** [comment]
I use `python -X utf8 -m markitdown` to solve this issue. I totally agreed how @jromal said, the UTF-8 should be default as always.

**Comment by afourney** [comment]
The reported stdout encoding crash is addressed on main. For saved Markdown, please use markitdown input.pdf -o output.md (with your actual input filename). The -o option introduced in #116 writes UTF-8 directly and preserves characters that the terminal cannot represent; terminal output may replace unsupported characters.

Closing this encoding report as resolved. Please ask to reopen if the crash persists with the updated code, including your version and complete traceback.
