### ISSUE TITLE
ValueError: numpy.dtype size changed

### ISSUE THREAD

**Issue by davidwoodburn** [microsoft/markitdown#149]
I get the following error trying to convert any pdf to md:

```
❯ markitdown notes.pdf > notes.md
Traceback (most recent call last):
  File "/Users/davidwoodburn/.config/python/bin/markitdown", line 5, in <module>
    from markitdown.__main__ import main
  File "/Users/davidwoodburn/.config/python/lib/python3.12/site-packages/markitdown/__init__.py", line 5, in <module>
    from ._markitdown import MarkItDown, FileConversionException, UnsupportedFormatException
  File "/Users/davidwoodburn/.config/python/lib/python3.12/site-packages/markitdown/_markitdown.py", line 22, in <module>
    import pandas as pd
  File "/Users/davidwoodburn/.config/python/lib/python3.12/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/Users/davidwoodburn/.config/python/lib/python3.12/site-packages/pandas/core/api.py", line 1, in <module>
    from pandas._libs import (
  File "/Users/davidwoodburn/.config/python/lib/python3.12/site-packages/pandas/_libs/__init__.py", line 18, in <module>
    from pandas._libs.interval import Interval
  File "interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by l-lumin** [comment]
could you try downgrading your NumPy version to 1.26.4? I think the issue might be caused by changes to the C API in NumPy 2.0

**Comment by davidwoodburn** [comment]
That worked. Thank you. Now, should being compatible with NumPy 2.0 be a separate issue?
