### ISSUE TITLE
'charmap' codec can't encode character '\u02da'

### ISSUE THREAD

**Issue by dr-graviton** [microsoft/markitdown#151]
Getting the following error when running a PDF. Tried a few and they all failed with the same error. 

PDF: https://www.cuit.columbia.edu/sites/default/files/content/iPhone%2015.pdf

```
C:\sandbox\markitdown>markitdown "iPhone 15.pdf" > iphone.md
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\um\.conda\envs\aifoundry\Scripts\markitdown.exe\__main__.py", line 7, in <module>
  File "C:\Users\um\.conda\envs\aifoundry\Lib\site-packages\markitdown\__main__.py", line 43, in main
    print(result.text_content)
  File "C:\Users\um\.conda\envs\aifoundry\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u02da' in position 1329: character maps to <undefined>
```

I'm on window 11, py 3.12

**Comment by movahhedi** [comment]
As said [here](https://github.com/microsoft/markitdown/issues/138#issuecomment-2553156636), set the environment variable of `PYTHONUTF8` to `1`.
```cmd
set PYTHONUTF8=1
```

**Comment by weyCC81** [comment]
_Duplicate:_ 
https://github.com/microsoft/markitdown/issues/313, https://github.com/microsoft/markitdown/issues/198#issuecomment-2560064593

_Issue:_
```
# UnicodeEncodeError: 'charmap' codec can't encode character '\u202f' in position 44138: character maps to <undefined>
# UnicodeEncodeError: 'charmap' codec can't encode character '\u200b' in position 121523: character maps to <undefined>
# UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 18064: character maps to <undefined>
# UnicodeEncodeError: 'charmap' codec can't encode character '\uf0e0' in position 11121: character maps to <undefined>
```

_Try:_ 
https://github.com/microsoft/markitdown/issues/151#issuecomment-2558081678 > did no work for me

_Solution:_ 
https://github.com/microsoft/markitdown/issues/138#issuecomment-2564166315 > worked

**Comment by afourney** [comment]
The reported stdout encoding crash is addressed on main. For saved Markdown, please use markitdown input.pdf -o output.md (with your actual input filename). The -o option introduced in #116 writes UTF-8 directly and preserves characters that the terminal cannot represent; terminal output may replace unsupported characters.

Closing this encoding report as resolved. Please ask to reopen if the crash persists with the updated code, including your version and complete traceback.
