### ISSUE TITLE
[bug] markitdown._markitdown.UnsupportedFormatException

### ISSUE THREAD

**Issue by doggy8088** [microsoft/markitdown#222]
Here is the steps to reproduce the issue:

OS: Windows

Shell: PowerShell v7.4.6

```ps1
pip install markitdown
curl -s https://www.duotify.com -o a.htm
type a.htm | markitdown
```

The error message:

```log
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\markitdown.exe\__main__.py", line 7, in <module>
  File "C:\Python312\Lib\site-packages\markitdown\__main__.py", line 38, in main
    result = markitdown.convert_stream(sys.stdin.buffer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\markitdown\_markitdown.py", line 1142, in convert_stream
    result = self._convert(temp_path, extensions, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\markitdown\_markitdown.py", line 1260, in _convert
    raise UnsupportedFormatException(
markitdown._markitdown.UnsupportedFormatException: Could not convert 'C:\Users\user\AppData\Local\Temp\tmpzn_zxenq' to Markdown. The formats [] are not supported.
```

**Comment by doggy8088** [comment]
I found that as long as the first few characters of the downloaded webpage are blank or line breaks, the program will crash, always showing the same error message.

It might be an issue with the logic for determining file type.

**Comment by afourney** [comment]
I am investigating. I think the problem must be lower in the stack, perhaps puremagic or similar. We shouldn't need to trim the input stream.

**Comment by afourney** [comment]
Fixed in #260
