### ISSUE TITLE
'res' variable not declared inside _convert before usage

### ISSUE THREAD

**Issue by dsimanis** [microsoft/markitdown#40]
`res` variable inside `MarkItDown` class `_convert` method is not declared before usage:

```
_markitdown.py", line 1045, in _convert
    if res is not None:
       ^^^
UnboundLocalError: cannot access local variable 'res' where it is not associated with a value
```

**Comment by gagb** [comment]
Can you please share more context for repro?

**Comment by sambartik** [comment]
> Can you please share more context for repro?

I got this error when I tried to convert a non-existing pdf file:

```python
from markitdown import MarkItDown

markitdown = MarkItDown()
result = markitdown.convert("file-that-doesnt-exist.pdf")
print(result.text_content)
```

**Comment by tarrasque73** [comment]
I have the same issue just by executing the sample code on github (using a PDF) and the file definitely exists

```
from markitdown import MarkItDown

markitdown = MarkItDown()
result = markitdown.convert("test.pdf")
print(result.text_content)
```

**Comment by sidesteps** [comment]
Getting same error for pdf file that exists in the current dir.

**Comment by sambartik** [comment]
> I have the same issue just by executing the sample code on github (using a PDF) and the file definitely exists
> 
> ```
> from markitdown import MarkItDown
> 
> markitdown = MarkItDown()
> result = markitdown.convert("test.pdf")
> print(result.text_content)
> ```

I can't reproduce your results. This exact code works for me with repo's example test.pdf in CWD.

Environment:
```
Python 3.13.1
macOS 15.1.1 x86_64
markitdown             0.0.1a2
```

**Comment by sidesteps** [comment]
With exact same code and test.pdf in cwd I get:

```
Traceback (most recent call last):
  File "/home/sstep/tomd/tomd.py", line 5, in <module>
    result = md.convert("test.pdf")
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sstep/tomd/.venv/lib/python3.12/site-packages/markitdown/_markitdown.py", line 902, in convert
    return self.convert_local(source, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sstep/tomd/.venv/lib/python3.12/site-packages/markitdown/_markitdown.py", line 922, in convert_local
    return self._convert(path, extensions, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sstep/tomd/.venv/lib/python3.12/site-packages/markitdown/_markitdown.py", line 1045, in _convert
    if res is not None:
       ^^^
UnboundLocalError: cannot access local variable 'res' where it is not associated with a value
```


```
Python 3.12.7
markitdown   0.0.1a2
Arch Linux 6.12.4-arch1-1
```

**Comment by tarrasque73** [comment]
> > I have the same issue just by executing the sample code on github (using a PDF) and the file definitely exists
> > ```
> > from markitdown import MarkItDown
> > 
> > markitdown = MarkItDown()
> > result = markitdown.convert("test.pdf")
> > print(result.text_content)
> > ```
> 
> I can't reproduce your results. This exact code works for me with repo's example test.pdf in CWD.
> 
> Environment:
> 
> ```
> Python 3.13.1
> macOS 15.1.1 x86_64
> markitdown             0.0.1a2
> ```

I'm using Python 3.12.8 on Win 11
