### ISSUE TITLE
### Audio Transcript: Error. Could not transcribe this audio.

### ISSUE THREAD

**Issue by caesarllj** [microsoft/markitdown#74]
### Audio Transcript:
Error. Could not transcribe this audio.

**Comment by Soulter** [comment]
Hi, can you provide more information about this?

**Comment by caesarllj** [comment]
from markitdown import MarkItDown
markitdown = MarkItDown()  
    
result = markitdown.convert("******.mp3")
print(result.text_content)

.xlsx .pdf no problem,.mp3 format file error prompt

### Audio Transcript:
Error. Could not transcribe this audio.

**Comment by tathagatankit** [comment]
I am also getting issues with audio files. I tired with .mp3 and .wav file format and getting the below issue:
![Image](https://github.com/user-attachments/assets/8419e184-fbba-4177-982f-807176ad6abf)

Additionally, I am using a Mac and noticed that exiftool was not installed during the pip installation. I’m unable to install this tool externally because macOS is blocking the installation and displaying a malware warning. Could someone assist with this? Your help would be greatly appreciated. Thank you!

**Comment by caesarllj** [comment]
> I am also getting issues with audio files. I tried with .mp3 and .wav file format and getting the below issue: ![Image](https://github.com/user-attachments/assets/8419e184-fbba-4177-982f-807176ad6abf)
> 
> Additionally, I am using a Mac and noticed that exiftool was not installed during the pip installation. I’m unable to install this tool externally because macOS is blocking the installation and displaying a malware warning. Could someone assist with this? Your help would be greatly appreciated. Thank you!

I am in window env,the reason for above problems is that I am unable to use google service.

**Comment by claudiocassimiro** [comment]
Have the same issue here, running in linux ubuntu

My error log:

➜ python3 test.py
Traceback (most recent call last):
  File "/home/claudio/Desktop/test.py", line 4, in <module>
    result = md.convert("SonhoGelado.mp3")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/claudio/miniconda3/lib/python3.12/site-packages/markitdown/_markitdown.py", line 260, in convert
    return self.convert_local(source, stream_info=stream_info, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/claudio/miniconda3/lib/python3.12/site-packages/markitdown/_markitdown.py", line 314, in convert_local
    return self._convert(file_stream=fh, stream_info_guesses=guesses, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/claudio/miniconda3/lib/python3.12/site-packages/markitdown/_markitdown.py", line 600, in _convert
    raise FileConversionException(attempts=failed_attempts)
markitdown._exceptions.FileConversionException: File conversion failed after 1 attempts:
 - AudioConverter threw UnknownValueError with message:

**Comment by umair313** [comment]
> Have the same issue here, running in linux ubuntu
> 
> My error log:
> 
> ➜ python3 test.py Traceback (most recent call last): File "/home/claudio/Desktop/test.py", line 4, in result = md.convert("SonhoGelado.mp3") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/claudio/miniconda3/lib/python3.12/site-packages/markitdown/_markitdown.py", line 260, in convert return self.convert_local(source, stream_info=stream_info, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/claudio/miniconda3/lib/python3.12/site-packages/markitdown/_markitdown.py", line 314, in convert_local return self._convert(file_stream=fh, stream_info_guesses=guesses, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/claudio/miniconda3/lib/python3.12/site-packages/markitdown/_markitdown.py", line 600, in _convert raise FileConversionException(attempts=failed_attempts) markitdown._exceptions.FileConversionException: File conversion failed after 1 attempts:
> 
> * AudioConverter threw UnknownValueError with message:

Any solution for this error
