### ISSUE TITLE
trouble with writing out markdown file

### ISSUE THREAD

**Issue by kentaroy47** [microsoft/markitdown#78]
related: https://github.com/microsoft/markitdown/pull/19

still having some issues with character decoding, working w/ Windows+Japanese environment.

`markitdown example.pdf` works fine, but gives the following error with `markitdown example.pdf > example.md`

```Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\kyosh\anaconda3\Scripts\markitdown.exe\__main__.py", line 7, in <module>
  File "C:\Users\kyosh\anaconda3\Lib\site-packages\markitdown\__main__.py", line 16, in main
    print(result.text_content)
UnicodeEncodeError: 'cp932' codec can't encode character '\ufb03' in position 509: illegal multibyte sequence
```

perhaps add some escape sequence in `main.py?` for unicode errors?

```python
    try:
        if len(sys.argv) == 1:
            markitdown = MarkItDown()
            result = markitdown.convert_stream(sys.stdin.buffer)
            print(result.text_content)
        elif len(sys.argv) == 2:
            markitdown = MarkItDown()
            result = markitdown.convert(sys.argv[1])
            print(result.text_content)
        else:
            sys.stderr.write("Usage message here\n")
    except UnicodeEncodeError:
        # Fallback handling if encoding still fails
        try:
            # Try to encode with replacement characters
            if isinstance(result.text_content, str):
                print(result.text_content.encode('utf-8', errors='replace').decode('utf-8'))
        except Exception as e:
            sys.stderr.write(f"Encoding error: {str(e)}\n")
```

**Comment by gagb** [comment]
Are you install from pip or main?

**Comment by kentaroy47** [comment]
@gagb 
Thanks for fast response!

I tried both pip and git+https://github.com/microsoft/markitdown, both gave the same errors.

**Comment by gagb** [comment]
Thanks, can you share the file?

**Comment by kentaroy47** [comment]
it seems to fail on every pdfs for me.

e.g. print of this issue like this.

```markitdown '.\trouble with writing out markdown file · Issue #78 · microsoft_markitdown.pdf' > test.md
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\kyosh\anaconda3\Scripts\markitdown.exe\__main__.py", line 7, in <module>
  File "C:\Users\kyosh\anaconda3\Lib\site-packages\markitdown\__main__.py", line 16, in main
    print(result.text_content)
UnicodeEncodeError: 'cp932' codec can't encode character '\xb7' in position 59: illegal multibyte sequence
```

[trouble with writing out markdown file · Issue #78 · microsoft_markitdown.pdf](https://github.com/user-attachments/files/18159386/trouble.with.writing.out.markdown.file.Issue.78.microsoft_markitdown.pdf)

**Comment by SigireddyBalasai** [comment]
> it seems to fail on every pdfs for me.
> 
> e.g. print of this issue like this.
> 
> ```
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Users\kyosh\anaconda3\Scripts\markitdown.exe\__main__.py", line 7, in <module>
>   File "C:\Users\kyosh\anaconda3\Lib\site-packages\markitdown\__main__.py", line 16, in main
>     print(result.text_content)
> UnicodeEncodeError: 'cp932' codec can't encode character '\xb7' in position 59: illegal multibyte sequence
> ```
> 
> [trouble with writing out markdown file · Issue #78 · microsoft_markitdown.pdf](https://github.com/user-attachments/files/18159386/trouble.with.writing.out.markdown.file.Issue.78.microsoft_markitdown.pdf)

it is workign with this pdf for me

**Comment by Soulter** [comment]
Hi, I think this is probably related to what terminal environment you are using.

If you are using Powershell, You can see my answer in https://github.com/microsoft/markitdown/issues/111 to get my solution

**Comment by movahhedi** [comment]
As said [here](https://github.com/microsoft/markitdown/issues/138#issuecomment-2553156636), set the environment variable of `PYTHONUTF8` to `1`.
```cmd
set PYTHONUTF8=1
```

**Comment by kentaroy47** [comment]
Thanks for the workarounds. Would be great to fix this without changing the environmental valuables..🤗

**Comment by kentaroy47** [comment]
#116 should solve this issue. thanks.
