### ISSUE TITLE
cannot convert pdf to md

### ISSUE THREAD

**Issue by 0xSaurabhx** [microsoft/markitdown#95]
command:
```bash
markitdown demo.pdf
```

Traceback (most recent call last):
  File "/home/user/.local/bin/markitdown", line 5, in <module>
    from markitdown.__main__ import main
  File "/home/user/.local/lib/python3.11/site-packages/markitdown/__init__.py", line 5, in <module>
    from ._markitdown import MarkItDown, FileConversionException, UnsupportedFormatException
  File "/home/user/.local/lib/python3.11/site-packages/markitdown/_markitdown.py", line 23, in <module>
    import pptx
  File "/home/user/.local/lib/python3.11/site-packages/pptx/__init__.py", line 9, in <module>
    from pptx.api import Presentation
  File "/home/user/.local/lib/python3.11/site-packages/pptx/api.py", line 14, in <module>
    from pptx.package import Package
  File "/home/user/.local/lib/python3.11/site-packages/pptx/package.py", line 11, in <module>
    from pptx.parts.image import Image, ImagePart
  File "/home/user/.local/lib/python3.11/site-packages/pptx/parts/image.py", line 10, in <module>
    from PIL import Image as PIL_Image
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 89, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)

**Comment by abdxzi** [comment]
May be Pillow package installation is corrupted. Try `pip install --no-cache-dir Pillow`

**Comment by afourney** [comment]
Hmmm. Seems like an issue with Pillow.

Arguably @gagb we should start pinning some of the dependency versions.

**Comment by Shivangbijalwan** [comment]
your pakage is not installed or the pakkage is currupted .........

**Comment by SigireddyBalasai** [comment]
just use pip install -U markitdown 

that way you will get latest version @Shivangbijalwan

**Comment by 0xSaurabhx** [comment]
> May be Pillow package installation is corrupted. Try `pip install --no-cache-dir Pillow`

This fixed my issue, thanks 👍
